# Generated by Django 3.1.2 on 2020-10-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationmodel',
            name='donation_id',
        ),
    ]
