# Generated by Django 3.1.2 on 2020-10-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_donationmodel_donation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmodel',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='categories',
            field=models.CharField(choices=[('clothes', 'clothes')], default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
