# Generated by Django 3.1.2 on 2020-10-20 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20201017_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('q1', models.CharField(choices=[('1', '9 - 12'), ('2', '1 - 5'), ('3', 'Any Time')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
