# Generated by Django 3.1.2 on 2020-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_volunteermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermodel',
            name='q1',
            field=models.CharField(choices=[('1', '9 - 12'), ('2', '1 - 5'), ('3', 'Any Time')], default=1, max_length=100),
        ),
    ]
