# Generated by Django 3.1.2 on 2020-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201020_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='q2',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='q3',
            field=models.TextField(default=''),
        ),
    ]
