# Generated by Django 3.1.2 on 2020-10-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201020_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteermodel',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='volunteermodel',
            name='lastname',
        ),
    ]
