# Generated by Django 3.1.2 on 2020-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_volunteermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('onhold', 'onhold')], default='onhold', max_length=100),
        ),
    ]
