# Generated by Django 3.1.2 on 2020-10-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_volunteermodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(choices=[('Founder', 'Founder'), ('Volunteer', 'Volunteer')], default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='categories',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('books', 'Books'), ('toys', 'Toys')], default=' ', max_length=100),
        ),
    ]
