# Generated by Django 3.1.2 on 2020-10-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201021_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
