# Generated by Django 3.1.2 on 2020-10-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201022_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberModel',
        ),
        migrations.DeleteModel(
            name='VolunteerModel',
        ),
    ]
