# Generated by Django 3.1.2 on 2020-10-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201022_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationmodel',
            name='quantity',
        ),
    ]
