# Generated by Django 3.1.2 on 2020-10-24 05:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_donationmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('clothes', 'Clothes'), ('books', 'Books'), ('toys', 'Toys')], default=' ', max_length=100),
        ),
    ]
