# Generated by Django 3.1.2 on 2020-10-26 07:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201024_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('clothes', 'Clothes'), ('books', 'Books'), ('toys', 'Toys'), ('educate_kids', 'Educate Kids')], default=' ', max_length=100),
        ),
    ]
