# Generated by Django 3.1.2 on 2020-10-22 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(choices=[('Founder', 'Founder'), ('Volunteer', 'Volunteer')], default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='volunteers')),
                ('q1', models.CharField(choices=[('1', '9 - 12'), ('2', '1 - 5'), ('3', 'Any Time')], default=1, max_length=100)),
                ('q2', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default=1, max_length=100)),
                ('q3', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('onhold', 'onhold')], default='onhold', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
