# Generated by Django 3.1.2 on 2020-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='position',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='q1',
            field=models.CharField(choices=[('9 - 12', '9 - 12'), ('1 - 5', '1 - 5'), ('Any Time', 'Any Time')], default='9 - 12', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteermodel',
            name='q2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
    ]
