# Generated by Django 3.1.2 on 2020-10-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20201023_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteermodel',
            name='status',
        ),
    ]
