# Generated by Django 3.1.2 on 2020-10-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201026_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
