# Generated by Django 3.1.2 on 2020-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201026_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
